<form action=login_post.php method=post>

	<!DOCTYPE html><!-- This site was created in Webflow. http://www.webflow.com--><!-- Last Published: Sun Oct 02 2016 05:19:09 GMT+0000 (UTC) --><html data-wf-domain="kimwoohyun-s-first-site-82c580.webflow.io" data-wf-page="57efe4286ceee4687292d1fb" data-wf-site="57efe4276ceee4687292d1f8" data-wf-status="1"><head><meta charset="utf-8"><title>SMART FARM</title><meta content="width=device-width, initial-scale=1" name="viewport"><meta content="Webflow" name="generator"><link href="https://daks2k3a4ib2z.cloudfront.net/57efe4276ceee4687292d1f8/css/kimwoohyun-s-first-site-82c580.webflow.92126a281.css" rel="stylesheet" type="text/css"><script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script><script type="text/javascript">WebFont.load({
		google: {
			families: ["Montserrat:400,700","Oswald:300,400,700","Roboto Condensed:regular,700"]
		}
		});</script><script src="https://daks2k3a4ib2z.cloudfront.net/0globals/modernizr-2.7.1.js" type="text/javascript"></script><link href="https://y7v4p6k4.ssl.hwcdn.net/placeholder/favicon.ico" rel="shortcut icon" type="image/x-icon"><link href="https://daks2k3a4ib2z.cloudfront.net/img/webclip.png" rel="apple-touch-icon"></head><body><div class="container w-container"><h1 class="logo w-hidden-tiny">SMARTFARM</h1><p class="subtitle"></p><div class="about w-hidden-main">SMART FARM</div><div class="join-wrapper w-clearfix w-hidden-main w-hidden-tiny"><div class="beta-line"></div><p class="join">Join Our <br><br>SMART FARM</p><div class="beta-line"></div></div><div class="sign-up-form w-form"><form data-name="Signup Form" name="wf-form-signup-form"><input class="field w-input" data-name="Email" maxlength="256" name="email" placeholder="Your email address" required="required" type="email"><input class="field w-input" data-name="Email" maxlength="256" name="pw" placeholder="PASSWORD" required="required" type="password"><input class="button w-button" data-wait="Please wait..." type="submit" value="Submit"></form><div class="success-message w-form-done"><p>Thanks! You have been added to our beta list.&nbsp;</p><p class="spread-word">Help spread the word!</p><div class="social-widget-wrapper w-clearfix"><div class="social-widget w-widget w-widget-twitter"><iframe src="//platform.twitter.com/widgets/tweet_button.html#url=http%3A%2F%2Fwebflow.com&amp;counturl=webflow.com&amp;text=Check%20out%20this%20site&amp;count=horizontal&amp;size=m&amp;dnt=true" scrolling="no" frameborder="0" allowtransparency="true" style="border: none; overflow: hidden; width: 62px; height: 21px;"></iframe><div class="w-widget-twitter-count-shim"><div class="w-widget-twitter-count-inner">...</div></div></div><div class="social-widget w-widget w-widget-facebook"><iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Ffacebook.com%2Fwebflow&amp;layout=button_count&amp;locale=en_US&amp;action=like&amp;show_faces=false&amp;share=false" scrolling="no" frameborder="0" allowtransparency="true" style="border: none; overflow: hidden; width: 90px; height: 20px;"></iframe></div></div></div><div class="error-message w-form-fail"><p>&nbsp;</div></div><div class="align-right w-col w-col-6 w-col-small-6">
</a></a></a></div></div></div></div><script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js" type="text/javascript"></script>

<!--[if lte IE 9]><script src="//cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->
</body></html>
</form>